#!/bin/sh
mount -t btrfs LABEL=sp6-backup /mnt || exit 1
mount -t btrfs UUID=76c2d8f7-278d-428c-9a42-571216cc0773 /btrfs || (umount /mnt; exit 1 )
cd /btrfs
btrfs-subvolume-backup --local snapshots --last "" \@sp6-home /mnt/snapshots || echo Blad backupu home.
btrfs-subvolume-backup --local snapshots --last "" \@sp6-root /mnt/snapshots || echo Blad backupu root.
btrfs-subvolume-backup --local snapshots --last "" \@sp6-www /mnt/snapshots || echo Blad backupu www.
cd /var/lib/lxc
for i in *; do
  if [ -d $i ]; then
    if [ ! -f $i/btrfs-initially-synced ]; then 
      btrfs-subvolume-backup --init --local /btrfs/snapshots --last "" $i/rootfs /mnt/snapshots && touch $i/btrfs-initially-synced
    else
      btrfs-subvolume-backup --local /btrfs/snapshots --last "" $i/rootfs /mnt/snapshots
    fi
  fi
done
sleep 10
umount /mnt || echo "Blad odmontowania dysku zewnetrznego. Odmontuj /mnt recznie (umount /mnt) po zamknieciu aplikacji korzystajacych z niego."
umount /btrfs || echo "Blad odmontowania dysku serwera. Odmontuj /btrfs recznie (umount /btrfs) po zamknieciu aplikacji korzystajacych z niego."

